### ISSUE TITLE
"Why cant I access your website? I want to purchase your products"

### ISSUE THREAD

**Issue by ScooterSam** [woganmay/laravel-gdpr-blocker#1]
I can totally understand why it makes sense to do this, but it's so unfair, I'm British, I'm also a web developer. 

Why should we stop people visiting our site and using the cool things we have built? 

Would it not make more sense to start building packages to help with adding GDPR compliance, rather than just blocking people from the EU?

I'm personally going to be going down this route^ and any packages I do make, I will be releasing, but atleast consider this. 

This method is just lazy and extremely unfair to the internet users.

**Comment by woganmay** [comment]
https://twitter.com/WoganMay/status/992792691527356417
